server:
  port: 10010 # 网关
spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
zuul:
  prefix: /api # 路由前缀
  routes:
    item-service: /item/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 熔断超时时长 5000ms

ribbon:
  ConnectTimeout: 1000 # ribbon连接超时时长
  ReadTimeout: 3500 # ribbon 读取超时时长
  MaxAutoRetries: 0 # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 #服务切换重试次数
